// The picture on the learning card, against a real Chromium with the unpacked
// extension loaded.
//
// The load-bearing case is the second page. A content script's tooltip lives in
// the host page's DOM, so an <img> inside it answers to the SITE's img-src, not
// to ours - which is why hotlinking to an image host would come up blank on
// every strict site on the web. Bundling and addressing the file through
// chrome.runtime.getURL is supposed to sidestep that entirely, because the
// chrome-extension: scheme is exempt from the page's policy.
//
// "Supposed to" is the reason this file exists. If the CSP case goes red the
// design is wrong, not the test.
//
// Fixtures: if vis/ is empty this script draws its own placeholder pictures
// first, with a throwaway Chromium, and deletes them on the way out. Real
// artwork is generated by the dataset pipeline and committed; placeholders are
// not, because a checked-in gradient claiming to illustrate "abolish" is worse
// than no picture at all. Either way the test runs.
import { chromium } from 'playwright';
import http from 'node:http';
import path from 'node:path';
import fs from 'node:fs';
import { createRequire } from 'node:module';

const EXT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const require = createRequire(import.meta.url);
const C = require(path.join(EXT, 'lib/vocab-core.js'));
const Visual = require(path.join(EXT, 'lib/visual.js'));

const VIS_DIR = path.join(EXT, 'vis');
const INDEX_FILE = path.join(EXT, 'visual-index.json');

/** Slugs for the first `n` C1 entries, computed the way the browser will. */
function firstSlugs(n) {
    const rows = C.parseCSV(fs.readFileSync(path.join(EXT, 'dataset-C1.csv'), 'utf8'))
        .filter(C.validateEntry).slice(0, n);
    return rows.map(r => Visual.slugFor(C.normalizeEntry(r, 'c1')));
}

/**
 * Draw placeholder pictures, and say what to delete afterwards.
 *
 * Nothing in this repo encodes an image and the pipeline that will (sharp) runs
 * on a developer's machine, so the encoder used here is the browser: a canvas
 * and toDataURL('image/webp') produce real WebP bytes, which is all the test
 * needs - it asserts that a file decodes, not that it is beautiful.
 */
async function makeFixtures() {
    const hadVis = fs.existsSync(VIS_DIR) &&
        fs.readdirSync(VIS_DIR).some(f => /\.(avif|webp)$/.test(f));
    if (hadVis) return { made: [], indexWritten: false };

    const slugs = firstSlugs(5);
    fs.mkdirSync(VIS_DIR, { recursive: true });

    const browser = await chromium.launch({
        executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium'
    });
    const page = await browser.newPage();
    const made = [];
    for (const [i, slug] of slugs.entries()) {
        const dataUrl = await page.evaluate(({ hue }) => {
            const c = document.createElement('canvas');
            c.width = 320; c.height = 160;
            const g = c.getContext('2d');
            const grad = g.createLinearGradient(0, 0, 320, 160);
            grad.addColorStop(0, `hsl(${hue} 70% 45%)`);
            grad.addColorStop(1, `hsl(${hue + 40} 65% 62%)`);
            g.fillStyle = grad; g.fillRect(0, 0, 320, 160);
            g.fillStyle = 'rgba(255,255,255,.85)';
            for (let x = 10; x < 320; x += 26) for (let y = 10; y < 160; y += 26) g.fillRect(x, y, 6, 6);
            return c.toDataURL('image/webp', 0.5);
        }, { hue: (i * 47) % 360 });
        const file = path.join(VIS_DIR, slug + '.webp');
        fs.writeFileSync(file, Buffer.from(dataUrl.split(',')[1], 'base64'));
        made.push(file);
    }
    await browser.close();

    const indexWritten = !fs.existsSync(INDEX_FILE);
    if (indexWritten) {
        fs.writeFileSync(INDEX_FILE, JSON.stringify({
            v: 1, generated: new Date().toISOString().slice(0, 10),
            fmt: 'webp', dim: [320, 160], photo: slugs, icon: {}
        }, null, 2) + '\n');
    }
    return { made, indexWritten };
}

const fixtures = await makeFixtures();
function cleanUpFixtures() {
    for (const f of fixtures.made) { try { fs.unlinkSync(f); } catch (e) { /* gone */ } }
    if (fixtures.made.length) { try { fs.rmdirSync(VIS_DIR); } catch (e) { /* not empty */ } }
    if (fixtures.indexWritten) { try { fs.unlinkSync(INDEX_FILE); } catch (e) { /* gone */ } }
}
process.on('exit', cleanUpFixtures);

const PHOTO_SLUGS = new Set(
    fs.existsSync(INDEX_FILE)
        ? (JSON.parse(fs.readFileSync(INDEX_FILE, 'utf8')).photo || [])
        : []);
/** Does this headword have a bundled picture, according to the shipped index? */
function hasPhoto(word) {
    const rows = C.parseCSV(fs.readFileSync(path.join(EXT, 'dataset-C1.csv'), 'utf8'))
        .filter(C.validateEntry);
    const row = rows.find(r => r.word === word);
    return !!row && PHOTO_SLUGS.has(Visual.slugFor(C.normalizeEntry(row, 'c1')));
}

// Vietnamese meanings lifted from dataset-C1.csv so the matching is real.
// "bãi bỏ" -> abolish and "sự vắng mặt" -> absence are the two with a bundled
// picture; the rest are there to be drawn as concept glyphs.
//
// Long on purpose. The whole page counts as one "post", and the per-post word
// budget scales with how much prose the post has - a four-paragraph fixture
// gets two words through and cannot show both a photo and a glyph.
const BODY = `
<h1>Một vài ghi chép về chính sách</h1>
<p>Bãi bỏ quy định cũ là điều cần thiết trong giai đoạn này, khi các doanh
nghiệp đang phải đối mặt với quá nhiều thủ tục chồng chéo và tốn kém.</p>
<p>Sự vắng mặt của ông ấy khiến cuộc họp phải hoãn lại, và không ai trong ban
tổ chức biết chắc khi nào chương trình mới có thể tiếp tục được.</p>
<p>Việc lạm dụng quyền lực đã bị phát hiện từ sớm, nhưng phải mất nhiều tháng
thì các cơ quan liên quan mới đưa ra được kết luận cuối cùng về vụ việc.</p>
<p>Nhiều người cho rằng lập luận đó là vô lý, bởi nó bỏ qua gần như toàn bộ
những dữ liệu đã được công bố rộng rãi trong hai năm vừa qua.</p>
<p>Nguồn tài nguyên dồi dào của khu vực này từng được xem là lợi thế lớn nhất,
song cách khai thác thiếu tính toán đang dần làm cạn kiệt nó.</p>
<p>Học viện vừa công bố kế hoạch mở rộng, với mục tiêu tăng tốc quá trình đào
tạo và giúp chương trình trở nên dễ tiếp cận hơn với sinh viên ở xa.</p>
<p>Sự chấp nhận của cộng đồng đối với thay đổi này diễn ra chậm hơn dự kiến,
dù những thành tựu ban đầu đã được ghi nhận một cách rõ ràng.</p>
<p>Nhiều doanh nghiệp đã cân nhắc kỹ trước khi đưa ra lựa chọn, vì họ hiểu rằng
một quyết định sai ở thời điểm này sẽ kéo theo hậu quả lâu dài.</p>`;

function page(extraHead = '') {
    return `<!doctype html><html lang="vi"><head><meta charset="utf-8">
<title>Thử nghiệm</title>${extraHead}</head><body>${BODY}</body></html>`;
}

// Three fixtures, three different things that could break the picture.
const ROUTES = {
    // 1. An ordinary page. Baseline.
    '/plain': { head: '', headers: {} },
    // 2. A site that forbids third-party images. This is the one that matters.
    '/strict': { head: '', headers: { 'Content-Security-Policy': "img-src 'self'; default-src 'self' 'unsafe-inline'" } },
    // 3. A site whose reset fights us for the <img> box. `height: auto
    //    !important` beats a class selector, and would resize the card after it
    //    had already been positioned - so the strip is sized by its container,
    //    not by the image.
    '/hostile-css': { head: '<style>img{height:auto!important;max-width:100%!important;width:auto!important}</style>', headers: {} }
};

const server = http.createServer((req, res) => {
    const route = ROUTES[new URL(req.url, 'http://x').pathname] || ROUTES['/plain'];
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', ...route.headers });
    res.end(page(route.head));
});
await new Promise(r => server.listen(0, r));
const base = `http://127.0.0.1:${server.address().port}`;

const ctx = await chromium.launchPersistentContext(
    path.join(process.env.TMPDIR || '/tmp', 'merid-visual-' + Date.now()),
    {
        headless: true,
        executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium',
        args: [`--disable-extensions-except=${EXT}`, `--load-extension=${EXT}`]
    }
);

// The worker starts on its own, but not always before the first page does.
if (!ctx.serviceWorkers().length) await ctx.waitForEvent('serviceworker', { timeout: 20000 });

const fail = [];
const ok = [];
const check = (cond, label, extra = '') => (cond ? ok : fail).push(label + (extra ? ` -> ${extra}` : ''));

async function openHighlighted(url) {
    const p = await ctx.newPage();
    await p.goto(url, { waitUntil: 'domcontentloaded' });
    await p.waitForSelector('.vocab-master-highlight', { timeout: 20000 }).catch(() => { });
    return p;
}

/**
 * Open the card for `word`.
 *
 * A real pointer move is the wrong tool here: an already-open card sits over
 * the page and swallows the hover meant for the next span, so playwright waits
 * out its whole retry budget on an element that is genuinely covered. The
 * extension listens for `mouseover` on document, so dispatching one says the
 * same thing without fighting the layout - which is how e2e/interaction.mjs
 * drives it too.
 */
async function hover(p, word) {
    const found = await p.evaluate((w) => {
        const el = document.querySelector(`.vocab-master-highlight[data-word="${w}"]`);
        if (!el) return false;
        el.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
        return true;
    }, word);
    if (!found) return null;
    await p.waitForSelector('.vocab-master-tooltip .vm-card', { timeout: 5000 }).catch(() => { });
    return true;
}

/** Wait for whatever picture is on the open card to finish loading (or fail). */
async function settled(p) {
    await p.waitForFunction(() => {
        const i = document.querySelector('.vm-visual-img');
        return !i || i.complete;
    }, { timeout: 5000 }).catch(() => { });
}

// ---------------------------------------------------------------------------
// 1. Baseline: a bundled picture decodes on an ordinary page.
// ---------------------------------------------------------------------------
{
    const p = await openHighlighted(base + '/plain');
    const words = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.dataset.word));
    check(words.length > 0, 'page has highlighted words', words.join(','));

    const withPhoto = words.find(hasPhoto);
    if (withPhoto) {
        await hover(p, withPhoto);
        const img = await p.$('.vocab-master-tooltip .vm-visual-img');
        check(!!img, `card for "${withPhoto}" has a picture element`);
        if (img) {
            const src = await img.getAttribute('src');
            check(/^chrome-extension:\/\//.test(src || ''), 'picture is addressed through the extension', src);
            // The assertion that actually means something. A correct src with a
            // broken file still passes "the element exists".
            await settled(p);
            const w = await img.evaluate(i => i.naturalWidth);
            check(w > 0, 'picture actually decoded on a plain page', `naturalWidth=${w}`);
            const ready = await img.evaluate(i => i.classList.contains('vm-ready'));
            check(ready, 'picture faded in (load handler ran)');
        }
    } else {
        check(false, 'a word with a bundled picture appeared on the page', words.join(','));
    }
    await p.close();
}

// ---------------------------------------------------------------------------
// 2. THE ONE THAT MATTERS: a site that allows same-origin images only.
// ---------------------------------------------------------------------------
{
    const p = await openHighlighted(base + '/strict');
    const words = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.dataset.word));
    const withPhoto = words.find(hasPhoto);
    if (withPhoto) {
        await hover(p, withPhoto);
        const img = await p.$('.vocab-master-tooltip .vm-visual-img');
        check(!!img, 'card still has a picture element under img-src \'self\'');
        if (img) {
            await settled(p);
            const w = await img.evaluate(i => i.naturalWidth);
            check(w > 0, "picture decoded despite the page's img-src 'self'", `naturalWidth=${w}`);
        }
    } else {
        check(false, 'a word with a bundled picture appeared on the strict page', words.join(','));
    }
    await p.close();
}

// ---------------------------------------------------------------------------
// 3. A hostile image reset must not move a card that is already placed.
// ---------------------------------------------------------------------------
{
    const p = await openHighlighted(base + '/hostile-css');
    const words = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.dataset.word));
    const withPhoto = words.find(hasPhoto);
    if (withPhoto) {
        // Measure the moment the card appears, then again once the picture is in.
        await hover(p, withPhoto);
        const before = await p.$eval('.vocab-master-tooltip', el => el.getBoundingClientRect().height);
        await settled(p);
        const after = await p.$eval('.vocab-master-tooltip', el => el.getBoundingClientRect().height);
        check(Math.abs(after - before) < 1,
            'card height is settled before the picture arrives', `${before} -> ${after}`);
        const w = await p.$eval('.vm-visual-img', i => i.naturalWidth).catch(() => 0);
        check(w > 0, 'picture decoded despite the page fighting for the <img> box');
    } else {
        check(false, 'a word with a bundled picture appeared on the hostile-css page', words.join(','));
    }
    await p.close();
}

// ---------------------------------------------------------------------------
// 4. An abstract word gets a glyph, not an empty box.
// ---------------------------------------------------------------------------
{
    const p = await openHighlighted(base + '/plain');
    const words = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.dataset.word));
    // Which words have a picture is a property of vis/, not something to
    // hard-code here: ask each card what it actually drew.
    let sawGlyph = null;
    for (const word of words) {
        await hover(p, word);
        const kind = await p.$eval('.vocab-master-tooltip .vm-visual',
            el => el.className).catch(() => null);
        check(!!kind, `card for "${word}" has an artwork box`, String(kind));
        if (kind && /vm-visual--(icon|generic)/.test(kind)) { sawGlyph = word; break; }
    }
    check(!!sawGlyph, 'at least one word drew a glyph rather than a photo', words.join(','));
    if (sawGlyph) {
        const box = await p.$('.vocab-master-tooltip .vm-visual');
        const hue = await box.evaluate(el => el.style.getPropertyValue('--vm-vis-hue'));
        const angle = await box.evaluate(el => el.style.getPropertyValue('--vm-vis-angle'));
        const pat = await box.evaluate(el => el.dataset.vmPat);
        check(hue !== '' && angle !== '' && pat !== undefined,
            'glyph box carries all three generated axes', `hue=${hue} angle=${angle} pat=${pat}`);
        const drawn = await box.evaluate(el => !!el.querySelector('svg, .vm-visual-letter'));
        check(drawn, 'glyph box is not empty');
        const noImg = await box.evaluate(el => !el.querySelector('img'));
        check(noImg, 'glyph box asks for no image at all');
    }
    await p.close();
}

// ---------------------------------------------------------------------------
// 5. Card stays on screen on a short window, at the bottom of the page.
// ---------------------------------------------------------------------------
{
    const p = await ctx.newPage();
    await p.setViewportSize({ width: 900, height: 560 });
    await p.goto(base + '/plain', { waitUntil: 'domcontentloaded' });
    await p.waitForSelector('.vocab-master-highlight', { timeout: 20000 }).catch(() => { });
    const spans = await p.$$('.vocab-master-highlight');
    if (spans.length) {
        await spans[spans.length - 1].scrollIntoViewIfNeeded();
        await p.evaluate(() => {
            const els = document.querySelectorAll('.vocab-master-highlight');
            els[els.length - 1].dispatchEvent(new MouseEvent('mouseover', { bubbles: true }));
        });
        await p.waitForSelector('.vocab-master-tooltip .vm-card', { timeout: 5000 }).catch(() => { });
        const box = await p.$eval('.vocab-master-tooltip', el => {
            const r = el.getBoundingClientRect();
            return { top: r.top, bottom: r.bottom, vh: window.innerHeight };
        });
        check(box.top >= -1, 'card does not run off the top', JSON.stringify(box));
        check(box.bottom <= box.vh + 1, 'card does not run off the bottom', JSON.stringify(box));
    } else {
        check(false, 'short viewport page had highlighted words');
    }
    await p.close();
}

// ---------------------------------------------------------------------------
// 6. Turning the setting off removes the picture and leaves the page alone.
// ---------------------------------------------------------------------------
{
    const p = await openHighlighted(base + '/plain');
    const before = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.textContent));
    // page.evaluate runs in the page's world, which has no `chrome` - the
    // content script lives in an isolated one. The worker does have it, and
    // writing there is also the honest path: it is where the Settings page
    // writes too, so the content script hears about it the same way.
    const [worker] = ctx.serviceWorkers();
    await worker.evaluate(() => new Promise(r => chrome.storage.sync.set({ visualsEnabled: false }, r)));
    await p.waitForTimeout(400);
    const after = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.textContent));
    check(JSON.stringify(before) === JSON.stringify(after),
        'turning pictures off does not rewrite the page');

    const words = await p.$$eval('.vocab-master-highlight', els => els.map(e => e.dataset.word));
    if (words.length) {
        await hover(p, words[0]);
        const box = await p.$('.vocab-master-tooltip .vm-visual');
        check(!box, 'no artwork box once the setting is off');
        const card = await p.$('.vocab-master-tooltip .vm-card');
        check(!!card, 'the rest of the card is untouched');
    }
    await p.close();
}

await ctx.close();
server.close();
cleanUpFixtures();

console.log('\n--- passed ---');
for (const o of ok) console.log('  ok   ' + o);
if (fail.length) {
    console.log('\n--- FAILED ---');
    for (const f of fail) console.log('  FAIL ' + f);
}
console.log(`\n${ok.length} passed, ${fail.length} failed`);
process.exit(fail.length ? 1 : 0);
