// GENERATED by scripts/trace-mark.js from brand/merid-icon-dark-1024.png.
// Do not hand-edit: re-run the script, which also pixel-diffs the result
// against the master PNG so the vector can never drift from the artwork.

/** viewBox side length the coordinates below are expressed in. */
export const VIEW = 512

/** The rounded tile that backs the mark on light surfaces. */
export const TILE = { x: 0, y: 0, w: 512, h: 512, r: 110 }

/** The gold highlight bar struck through the M. */
export const BAR = { x: 84.81, y: 251.5, w: 342.37, h: 94.57, r: 6.71 }

/** The M itself, drawn over the bar. */
export const M_PATH = 'M143.75 138.63L143.75 368.5L196.88 368.5L196.88 220.88L238.88 316.38L288.63 316.38L330.63 221.5L330.63 368.5L383.75 368.5L383.75 138.63L313.5 138.63L264.13 250.63L216.5 138.63Z'
